# Site settings
title: "WTF - Now say What's the Fun!"
author: "Balajee Mohan"
description: "This is a blog about software, some mathematics, and the occasional philosophy. Not necessarily in that order."
keywords: "Spring, Spring Boot, SpringBoot, Spring Cloud, SpringCloud, Maven, Philosophy, Java, RxJava, Puzzles"
biography: "I am a Software Engineer, based out of Bangalore, India, who is passionate about puzzles and programming. The world around us is so vast, there is so much to explore. But perspective adds so much flavor to reality. I always believe addressing the root case is more important than addressing the symptoms. So it's always good to get down to the roots. Here you can find my <a href='/assets/cv.pdf'>Résumé</a>. Hop in as we explore the fun around us."
colophon: "© MMXIII — MMXVI by Hugo Sereno Ferreira.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "http://www.balajeetm.com/"

twitter_username: balajeetm
github_username: balajeetm
linkedin_username: balajeetm

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
