# Site settings
title: "WTF - What's the F**!"
author: "Balajee Mohan"
description: "After Monday and Tuesday, even the calendar says 'WTF'.<br><br>Well, WTF - disappointingly for some, is an acronym of 'What's The Fun?'<br><br>Yeah, you got it right, we don’t like cliché's, do we? So if you share the same aversion to cliché's, then you came to the right place.<br><br>Stand out of the crowd.<br>Remove the jargon, take out the abstraction, discard the sugarcoats!<br>Come Let's have fun!<br>Let's unjargon!"
keywords: "Spring, Spring Boot, SpringBoot, Spring Cloud, SpringCloud, Maven, Philosophy, Java, RxJava, Puzzles"
biography: "I am a Software Engineer, based out of Bangalore, India, who is passionate about puzzles and programming.<br><br>The world around us is so vast, there is so much to explore. But perspective adds so much flavor to reality.<br>I always believe addressing the root case is more important than addressing the symptoms. So it's always good to get down to the roots.<br><br>Here you can find my <a href='/assets/Resume_Balajee_T_M_Sr_Technical_Lead_Cisco_2017.pdf'>Résumé</a>.<br>Hop in as we explore the fun around us."
colophon: "© MMXIII — MMXVI by Hugo Sereno Ferreira.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "http://www.balajeetm.com/"

twitter_username: balajeetm
github_username: balajeetm
linkedin_username: balajeetm

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
